import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {connect} from './cdp-test.mjs';
const c=await connect(process.argv[2]),dir=new URL('../docs/exit-2026-10-07/',import.meta.url);mkdirSync(dir,{recursive:true});
const saved=await c.evaluate(`Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('traffic-jam-')).map(k=>[k,localStorage.getItem(k)]))`);
const snap=()=>c.evaluate(`document.querySelector('.garage-canvas').garageInspection.snapshot()`);
const ready=()=>c.until(`(()=>{const s=document.querySelector('.garage-canvas')?.garageInspection?.snapshot();return s?.ready&&s.sceneKey===s.performance.renderedSceneKey&&document.querySelector('.game-column').getAttribute('aria-busy')==='false'})()`);
async function reload(code){const t=await c.evaluate('performance.timeOrigin');await c.evaluate(code+';location.reload()');await c.until(`performance.timeOrigin!==${t}`);await ready();}
async function shot(name){writeFileSync(new URL(name+'.png',dir),Buffer.from((await c.send('Page.captureScreenshot')).data,'base64'));}
async function mouse(p,type){await c.send('Input.dispatchMouseEvent',{type,x:p.x,y:p.y,button:'left',buttons:type==='mouseReleased'?0:1,clickCount:1});}
async function button(text){const p=await c.evaluate(`(()=>{const b=[...(document.querySelector('.win-card')||document).querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)}||b.getAttribute('aria-label')===${JSON.stringify(text)});if(!b||b.disabled)throw Error('Unavailable '+${JSON.stringify(text)});const r=b.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;if(!b.contains(document.elementFromPoint(x,y)))throw Error('Obscured '+${JSON.stringify(text)});return{x,y}})()`);await mouse(p,'mousePressed');await mouse(p,'mouseReleased');await c.sleep(180);}
async function escape(touch=false,id='target',delta=4){const moves=await c.evaluate(`Number(document.querySelector('.stats b').textContent)`);const p=await c.evaluate(`(()=>{const a=document.querySelector('.garage-canvas').garageInspection,car=a.snapshot().cars.find(c=>c.id===${JSON.stringify(id)}),[x,,z]=car.position;for(const h of [.45,.6,.8,1])for(const o of [0,-.2,.2]){const px=x+(car.dir==='H'?o:0),pz=z+(car.dir==='V'?o:0),from=a.project(px,h,pz);if(a.pick(from.x,from.y)===car.id)return{from,to:a.project(px+(car.dir==='H'?${delta}:0),h,pz+(car.dir==='V'?${delta}:0))};}throw Error('Unpickable car')})()`);
 const input=(type,p)=>touch?c.send('Input.dispatchTouchEvent',{type:({mousePressed:'touchStart',mouseMoved:'touchMove',mouseReleased:'touchEnd'})[type],touchPoints:type==='mouseReleased'?[]:[{...p,id:1}]}):mouse(p,type);
 await input('mousePressed',p.from);for(let i=1;i<=12;i++){await input('mouseMoved',{x:p.from.x+(p.to.x-p.from.x)*i/12,y:p.from.y+(p.to.y-p.from.y)*i/12});await c.sleep(25);}await input('mouseReleased',p.to);await c.until(`Number(document.querySelector('.stats b').textContent)===${moves+1}`);await c.sleep(220);
}
const errors=[];await c.send('Runtime.enable');c.onEvent('Runtime.exceptionThrown',e=>errors.push(e.exceptionDetails.text));
const cars=[{id:'target',color:'#e53935',row:2,col:0,len:2,dir:'H'}];
const fixture=(pitch=65,yaw=0)=>`localStorage.setItem('traffic-jam-tutorial-v1',JSON.stringify({schema:1,data:true}));localStorage.setItem('traffic-jam-custom-levels-v2',JSON.stringify([{id:'custom-exit',title:'出庫演出',cars:${JSON.stringify(cars)}}]));localStorage.setItem('traffic-jam-session-v1',JSON.stringify({schema:1,data:{levelId:'custom-exit',cars:${JSON.stringify(cars)},history:[],moves:0}}));localStorage.setItem('traffic-jam-scene',JSON.stringify({pitch:${pitch},yaw:${yaw},zoom:1,quality:'high',theme:'day',motion:1.2}))`;
try{
 await c.send('Emulation.setFocusEmulationEnabled',{enabled:true});await c.send('Page.bringToFront');const results=[];
 for(const [name,width,height,pitch,yaw,touch] of [['desktop',1440,1000,65,0,false],['mobile',390,844,65,0,true],['low-angle',1440,1000,30,55,false]]){
 await c.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:touch});await c.send('Emulation.setTouchEmulationEnabled',{enabled:touch,maxTouchPoints:5});await reload(fixture(pitch,yaw));
 const initial=await snap(),storage=await c.evaluate(`localStorage.getItem('traffic-jam-scene')`);await escape(touch);const samples=[];let turnShot=false,driveShot=false;
 for(let i=0;i<45;i++){const s=await snap(),win=await c.evaluate(`!!document.querySelector('.win-card')`),car=s.cars.find(c=>c.id==='target');samples.push({age:s.exit.age,yaw:s.exit.yaw,position:car.position,wheel:car.wheelAngle,visible:s.exit.visible,complete:s.exit.complete,follow:s.cameraFollow,win});if(win){assert(s.exit.complete,'Result waits for animation completion');break;}if(s.exit.yaw<-.2&&!turnShot){turnShot=true;await shot(name+'-turn');}if(s.exit.yaw<-1.5&&!driveShot){driveShot=true;await shot(name+'-street');}await c.sleep(110);}
 await c.until(`!!document.querySelector('.win-card')`);const final=await snap();assert(turnShot&&driveShot);assert.equal(final.cameraFollow,0);assert.equal(final.exit.visible,false);assert.deepEqual(final.settings,initial.settings);assert.equal(await c.evaluate(`localStorage.getItem('traffic-jam-scene')`),storage);await shot(name+'-result');results.push({name,samples});
 await c.send('Emulation.setTouchEmulationEnabled',{enabled:false});await button('再玩一次');await c.until(`!document.querySelector('.level-transition')&&!document.querySelector('.win-card')`);await ready();const replay=await snap();assert.equal(replay.cars[0].position[0],1);assert.equal(replay.exit.yaw,0);assert.equal(replay.cameraFollow,0);
 }
 await c.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await reload(fixture());await escape();await c.until(`!!document.querySelector('.win-card')`);const reduced=await snap();assert.equal(reduced.cameraFollow,0);assert.equal(reduced.exit.yaw,0);assert(reduced.exit.age<1500);await shot('reduced-result');
 await c.send('Emulation.setEmulatedMedia',{features:[]});await reload(fixture());await button('編輯器');await ready();for(const col of [0,1]){const p=await c.evaluate(`document.querySelector('.garage-canvas').garageInspection.project(${col+.5},.06,2.5)`);await mouse(p,'mousePressed');await mouse(p,'mouseReleased');await c.sleep(150);}await button('試玩');await ready();await escape();await c.until(`!!document.querySelector('.win-card')`);await button('返回編輯器');await c.until(`!document.querySelector('.level-transition')`);await ready();assert.equal((await snap()).cars.length,1);
 await reload(`localStorage.removeItem('traffic-jam-session-v1');localStorage.setItem('traffic-jam-scene',JSON.stringify({pitch:65,yaw:0,zoom:1,quality:'high',theme:'day',motion:1.2}))`);
 const solution=JSON.parse(readFileSync(new URL('../public/levels/solutions.json',import.meta.url),'utf8'))['1'].solution.moves;
 for(const move of solution)await escape(false,move.carId,move.delta);
 await c.until(`!!document.querySelector('.win-card')`);await button('下一關');await c.until(`!document.querySelector('.level-transition')&&document.querySelector('.stage-heading')?.textContent.includes('02')`);await ready();assert.equal(await c.evaluate(`Number(document.querySelector('.stats b').textContent)`),0);
 assert.deepEqual(errors,[]);writeFileSync(new URL('results.json',dir),JSON.stringify({results,replayRestored:true,reducedMotion:true,trialReturn:true,officialNext:true,errors},null,2));console.log('Continuous exit, native mouse/touch wins, camera restoration, replay, trial return and official next level passed');
}finally{await c.send('Emulation.setEmulatedMedia',{features:[]});await c.send('Emulation.setTouchEmulationEnabled',{enabled:false});await c.send('Emulation.clearDeviceMetricsOverride');await c.evaluate(`for(const k of Object.keys(localStorage))if(k.startsWith('traffic-jam-'))localStorage.removeItem(k);for(const[k,v]of Object.entries(${JSON.stringify(saved)}))localStorage.setItem(k,v);location.reload()`);c.close();}
