import assert from 'node:assert/strict';
import {newRewards,unlockedRewards} from './gamePreferences.js';
import {snapDragDelta,quadDistance} from './pointerHelpers.js';
const result={completed:true,stars:3,perfect:true};
assert.deepEqual(newRewards({}, {'custom-1':result}),[]);
const first={1:result};
assert.deepEqual(newRewards({},first).map(r=>r.id),['first','three','perfect']);
assert.deepEqual(newRewards(first,first),[]);
assert.equal(unlockedRewards({1:{completed:true,stars:3}}).some(r=>r.id==='perfect'),false);
const nine=Object.fromEntries(Array.from({length:9},(_,i)=>[i+1,result]));
const ten={...nine,10:result};
assert.deepEqual(newRewards(nine,ten).map(r=>r.id),['ten','sunset']);
assert.equal(unlockedRewards({...ten,41:result,'01':result}).length,unlockedRewards(ten).length);
assert.equal(snapDragDelta(.2),0);assert.equal(snapDragDelta(.45),1);
assert.equal(snapDragDelta(-.45),-1);assert.equal(snapDragDelta(1.45),2);
const quad=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}];
assert.equal(quadDistance({x:5,y:5},quad),0);
assert.equal(quadDistance({x:14,y:5},quad),4);
assert.equal(quadDistance({x:13,y:14},quad),5);
console.log('Rewards, replay persistence and drag tolerance checks passed.');
